name: Docker Build and Push with Version

on:
  push:
    branches:
      - master

env:
  DOCKER_REGISTRY: r.evannregnault.dev
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Install cargo-semver
        uses: dtolnay/install@master
        with:
          crate: cargo-semver

      - name: Semver
        run:
          echo "VERSION=$(cargo semver get)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            user/app:latest
            user/app:1.0.0
            ${{ env.DOCKER_REGISTRY }}/obsessed-yanqing:latest
            ${{ env.DOCKER_REGISTRY }}/obsessed-yanqing:${{ env.VERSION }}